services:
  server:
    build: .
    container_name: $SERVER_HOST
    image: facundoveliz/vendo-backend
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - vendo

  nginx:
    build: ./nginx
    env_file: .env
    image: facundoveliz/vendo-nginx
    container_name: $NGINX_HOST
    restart: always
    ports:
      - $NGINX_PORT:$NGINX_PORT
    depends_on:
      - server
    networks:
      - budgie

  client:
    build: ./client
    container_name: $CLIENT_HOST
    image: facundoveliz/vendo-frontend
    env_file: .env
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    depends_on:
      - server
    networks:
      - vendo

networks:
  vendo:
